---
- name: Set sysctl config
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/30-ipforward.conf
    state: present
  loop:
    - name: net.ipv4.ip_forward
      value: "1"
    - name: net.ipv4.conf.all.forwarding
      value: "1"
    - name: net.ipv6.conf.all.forwarding
      value: "1"
- name: Create configuration
  block:
    - name: Create configuration directory
      ansible.builtin.file:
        path: /etc/wireguard
        mode: u=rwx,g=,o=
        owner: root
        group: root
        seuser: system_u
        serole: object_r
        setype: etc_t
    - name: Create configuration file
      ansible.builtin.template:
        src: wg.conf.j2
        dest: /etc/wireguard/{{ wg_interface }}.conf
        backup: true
        mode: u=rw,g=,o=
        owner: root
        group: root
        seuser: system_u
        serole: object_r
        setype: wireguard_exec_t
      register: config
- name: Restart server
  ansible.builtin.systemd:
    name: wg-quick@{{ wg_interface }}
    state: restarted
    enabled: true
