---
- name: Install wireguard-tools
  ansible.builtin.dnf:
    name: wireguard-tools
    state: present
- name: Set sysctl config
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/30-ipforward.conf
    state: present
  loop:
    - name: net.ipv4.ip_forward
      value: "1"
    - name: net.ipv4.conf.all.forwarding
      value: "1"
    - name: net.ipv6.conf.all.forwarding
      value: "1"
- name: Configure firewall
  block:
    - name: Enable firewall service
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: true
    - name: Set firewall options
      block:
        - name: Configure firewalld
          ansible.posix.firewalld:
            port: "{{ wg_server_port }}/udp"
            permanent: true
            immediate: true
            state: enabled
        - name: Configure masquerade for ip4
          ansible.posix.firewalld:
            rich_rule: rule family=ipv4 source address={{ wg_subnet4 }}/{{ wg_netmask4 }} masquerade
            permanent: true
            immediate: true
            state: enabled
        - name: Configure masquerade for ip6
          ansible.posix.firewalld:
            rich_rule: rule family=ipv6 source address={{ wg_subnet6 }}/{{ wg_netmask6 }} masquerade
            permanent: true
            immediate: true
            state: enabled
- name: Create configuration file
  ansible.builtin.template:
    src: wg.conf.j2
    dest: /etc/wireguard/{{ wg_interface }}.conf
    mode: u=rw,g=,o=
    owner: root
    group: root
    seuser: unconfined_u
    serole: object_r
    setype: etc_t
  register: config
- name: Restart server
  ansible.builtin.systemd:
    name: wg-quick@{{ wg_interface }}
    state: restarted
    enabled: true
