# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/9"
  config.vm.box_version = "3.0.0"
  config.vm.network "private_network", ip: "10.255.0.10"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
  config.vm.provision "ansible", playbook: "../ansible/server.yaml"
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
